In [7]:
import pandas as pd
df = pd.read_csv("emp_data.csv")
df

,Customer_ID,Name,Age,Gender,Department,Monthly_Income,City,Customer_Type,Latitude,Longitude,Purchase_Amount,Feedback
0,1630,Aarav Jadhav,36.0,Female,Finance,110390.0,Ahmednagar,New,17.536043,75.505984,62663.45,Good
1,1789,Neha Sharma,32.0,Female,Operations,39371.0,Ahmednagar,Regular,20.073236,75.947597,31790.01,Excellent
2,1685,Amit Joshi,53.0,Male,Marketing,38204.0,Kolhapur,New,20.852464,75.521740,91180.51,Average
3,1517,Amit Deshmukh,33.0,Female,Data Analytics,50382.0,Nagpur,Premium,20.430885,77.862365,1535.62,Average
4,1530,Rahul Pawar,58.0,Female,Operations,70249.0,Aurangabad,New,17.555342,73.493211,26105.84,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1107,Meera Chavan,46.0,Male,IT,49671.0,Pune,Regular,19.081121,78.961383,17574.52,Poor
996,1271,Sahil Joshi,24.0,Male,Marketing,25490.0,Mumbai,Premium,18.551581,76.760438,17463.15,Very Good
997,1861,Kavya Kulkarni,44.0,Male,Finance,31009.0,Kolhapur,New,16.723412,75.077469,41198.81,Poor
998,1436,Riya Patil,20.0,Male,Operations,15868.0,Ahmednagar,Regular,18.147135,75.114177,10314.42,Average
999,1103,Priya Deshmukh,36.0,Female,IT,38839.0,Pune,Premium,19.857801,75.029936,8918.73,Very Good

In [8]:
df.head()

,Customer_ID,Name,Age,Gender,Department,Monthly_Income,City,Customer_Type,Latitude,Longitude,Purchase_Amount,Feedback
0,1630,Aarav Jadhav,36.0,Female,Finance,110390.0,Ahmednagar,New,17.536043,75.505984,62663.45,Good
1,1789,Neha Sharma,32.0,Female,Operations,39371.0,Ahmednagar,Regular,20.073236,75.947597,31790.01,Excellent
2,1685,Amit Joshi,53.0,Male,Marketing,38204.0,Kolhapur,New,20.852464,75.521740,91180.51,Average
3,1517,Amit Deshmukh,33.0,Female,Data Analytics,50382.0,Nagpur,Premium,20.430885,77.862365,1535.62,Average
4,1530,Rahul Pawar,58.0,Female,Operations,70249.0,Aurangabad,New,17.555342,73.493211,26105.84,Good

In [9]:
df.tail()

,Customer_ID,Name,Age,Gender,Department,Monthly_Income,City,Customer_Type,Latitude,Longitude,Purchase_Amount,Feedback
995,1107,Meera Chavan,46.0,Male,IT,49671.0,Pune,Regular,19.081121,78.961383,17574.52,Poor
996,1271,Sahil Joshi,24.0,Male,Marketing,25490.0,Mumbai,Premium,18.551581,76.760438,17463.15,Very Good
997,1861,Kavya Kulkarni,44.0,Male,Finance,31009.0,Kolhapur,New,16.723412,75.077469,41198.81,Poor
998,1436,Riya Patil,20.0,Male,Operations,15868.0,Ahmednagar,Regular,18.147135,75.114177,10314.42,Average
999,1103,Priya Deshmukh,36.0,Female,IT,38839.0,Pune,Premium,19.857801,75.029936,8918.73,Very Good

In [11]:
df.shape

(1000, 12)

In [48]:
df.columns

Index(['Customer_ID', 'Name', 'Age', 'Gender', 'Department', 'Monthly_Income',
       'City', 'Customer_Type', 'Latitude', 'Longitude', 'Purchase_Amount',
       'Feedback'],
      dtype='str')

In [49]:
df.dtypes

Customer_ID          int64
Name                   str
Age                float64
Gender                 str
Department             str
Monthly_Income     float64
City                   str
Customer_Type          str
Latitude           float64
Longitude          float64
Purchase_Amount    float64
Feedback               str
dtype: object

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      1010 non-null   int64
 1   Name             1010 non-null   str
 2   Age              1010 non-null   float64
 3   Gender           1010 non-null   str
 4   Department       1010 non-null   str
 5   Monthly_Income   1010 non-null   float64
 6   City             1010 non-null   str
 7   Customer_Type    1010 non-null   str
 8   Latitude         1010 non-null   float64
 9   Longitude        1010 non-null   float64
 10  Purchase_Amount  1010 non-null   float64
 11  Feedback         1010 non-null   str
dtypes: float64(5), int64(1), str(6)
memory usage: 137.4 KB

In [51]:
df.describe()

,Customer_ID,Age,Monthly_Income,Latitude,Longitude,Purchase_Amount
count,1010.000000,1010.000000,1010.000000,1010.000000,1010.000000,1010.000000
mean,1499.883168,39.718812,68470.408911,19.010057,76.510804,49700.019218
std,288.602618,11.984055,29594.025390,1.425201,2.317686,29231.580533
min,1001.000000,18.000000,15012.000000,16.510429,72.515640,553.320000
25%,1250.250000,30.000000,43673.250000,17.797137,74.447227,24391.082500
50%,1498.500000,40.000000,68650.500000,19.013194,76.480344,48333.705000
75%,1750.750000,50.000000,93457.250000,20.232203,78.496075,74833.180000
max,2000.000000,60.000000,119969.000000,21.499106,80.474739,99995.440000

In [4]:
df.isnull().sum()

Customer_ID        0
Name               0
Age                0
Gender             0
Department         0
Monthly_Income     0
City               0
Customer_Type      0
Latitude           0
Longitude          0
Purchase_Amount    0
Feedback           0
dtype: int64

Duplicate Records

In [47]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1005    False
1006    False
1007    False
1008    False
1009    False
Length: 1010, dtype: bool

In [60]:
df[df.duplicated()]

,Customer_ID,Name,Age,Gender,Department,Monthly_Income,City,Customer_Type,Latitude,Longitude,Purchase_Amount,Feedback
399,1409,Unknown,51.0,Male,Sales,50268.0,Ahmednagar,Premium,20.612859,79.810018,43375.30,Poor
407,1779,Nikhil More,56.0,Female,Data Analytics,106812.0,Pune,Regular,17.119065,78.486322,4965.02,Excellent
449,1335,Amit Sharma,45.0,Female,Operations,44661.0,Nashik,New,17.561088,73.107108,49162.25,Very Good
529,1803,Rahul Shinde,23.0,Male,Marketing,43467.0,Nashik,New,17.462776,79.472924,4222.12,Very Good
547,1488,Sahil Patil,44.0,Male,Operations,39530.0,Aurangabad,Regular,20.068177,79.560447,85321.27,Poor
618,1095,Sneha Pawar,20.0,Female,IT,37356.0,Pune,Regular,20.618695,76.646362,44999.67,Good
819,1171,Sakshi Joshi,55.0,Female,Data Analytics,32548.0,Mumbai,New,17.103213,79.226236,27727.86,Excellent
893,1217,Aditya Joshi,33.0,Male,Data Analytics,69162.0,Kolhapur,Premium,21.015785,79.784344,95285.32,Excellent
907,1813,Isha Jadhav,23.0,Female,Operations,118733.0,Mumbai,Regular,16.890363,74.378241,71996.18,Excellent
949,1272,Meera Shinde,26.0,Male,Operations,94826.0,Thane,Regular,21.197091,78.054831,96987.98,Good

In [61]:
df.drop_duplicates(inplace = True)
df

,Customer_ID,Name,Age,Gender,Department,Monthly_Income,City,Customer_Type,Latitude,Longitude,Purchase_Amount,Feedback
0,1630,Aarav Jadhav,36.0,Female,Finance,110390.0,Ahmednagar,New,17.536043,75.505984,62663.45,Good
1,1789,Neha Sharma,32.0,Female,Operations,39371.0,Ahmednagar,Regular,20.073236,75.947597,31790.01,Excellent
2,1685,Amit Joshi,53.0,Male,Marketing,38204.0,Kolhapur,New,20.852464,75.521740,91180.51,Average
3,1517,Amit Deshmukh,33.0,Female,Data Analytics,50382.0,Nagpur,Premium,20.430885,77.862365,1535.62,Average
4,1530,Rahul Pawar,58.0,Female,Operations,70249.0,Aurangabad,New,17.555342,73.493211,26105.84,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
1005,1107,Meera Chavan,46.0,Male,IT,49671.0,Pune,Regular,19.081121,78.961383,17574.52,Poor
1006,1271,Sahil Joshi,24.0,Male,Marketing,25490.0,Mumbai,Premium,18.551581,76.760438,17463.15,Very Good
1007,1861,Kavya Kulkarni,44.0,Male,Finance,31009.0,Kolhapur,New,16.723412,75.077469,41198.81,Poor
1008,1436,Riya Patil,20.0,Male,Operations,15868.0,Ahmednagar,Regular,18.147135,75.114177,10314.42,Average
1009,1103,Priya Deshmukh,36.0,Female,IT,38839.0,Pune,Premium,19.857801,75.029936,8918.73,Very Good

In [62]:
df.duplicated().sum()

np.int64(0)

In [63]:
df.shape

(1000, 12)

In [64]:
df['Gender'].unique()

<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

In [66]:
# stadarize gender
df['Gender'] = df['Gender'].str.title()
df['Gender'].unique()

<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

In [67]:
# check numeic columns.
numeric_columns = [
    "Customer_ID",
    "Age",
    "Monthly_Income",
    "Latitude",
    "Longitude",
    "Purchase_Amount"
]

df[numeric_columns].dtypes

Customer_ID          int64
Age                float64
Monthly_Income     float64
Latitude           float64
Longitude          float64
Purchase_Amount    float64
dtype: object

In [12]:
# Handel missing age 

df['Age'].isnull().sum()

np.int64(0)

In [69]:
# fill missing age using the median.

df['Age']=df['Age'].fillna(df["Age"].median())

df["Age"].isnull().sum()

np.int64(0)

In [70]:
# Handle missing monthly income.

df['Monthly_Income']=df['Monthly_Income'].fillna(
    df["Monthly_Income"].median())

In [71]:
# Handel missing latitude.
df["Latitude"] = df["Latitude"].fillna(
    df["Latitude"].median()
)

In [72]:
# Handle missing longitude.
df["Longitude"] = df["Longitude"].fillna(
    df["Longitude"].median()
)

In [73]:
# handle missing purchasee amount 

df['Purchase_Amount'] = df['Purchase_Amount'].fillna(
    df['Purchase_Amount'].median()
)

In [74]:
# Handle missing Categorical values.
# Gender
df["Gender"]= df['Gender'].fillna(
    df['Gender'].mode()[0])

In [75]:
# Department
df["Department"] = df["Department"].fillna(
    df["Department"].mode()[0]
)

In [76]:
# City
df["City"] = df["City"].fillna(
    df["City"].mode()[0]
)

In [77]:
#Customer Type
df["Customer_Type"] = df["Customer_Type"].fillna(
    df["Customer_Type"].mode()[0]
)

In [78]:
# Feedback.
df["Feedback"]=df["Feedback"].fillna(
    df["Feedback"].mode()[0])

In [79]:
# Handel missing name
df["Name"] = df["Name"].fillna("Unknown")

In [80]:
# Final missing value check.
df.isnull().sum()

Customer_ID        0
Name               0
Age                0
Gender             0
Department         0
Monthly_Income     0
City               0
Customer_Type      0
Latitude           0
Longitude          0
Purchase_Amount    0
Feedback           0
dtype: int64

In [82]:
df.info()

<class 'pandas.DataFrame'>
Index: 1000 entries, 0 to 1009
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_ID      1000 non-null   int64
 1   Name             1000 non-null   str
 2   Age              1000 non-null   float64
 3   Gender           1000 non-null   str
 4   Department       1000 non-null   str
 5   Monthly_Income   1000 non-null   float64
 6   City             1000 non-null   str
 7   Customer_Type    1000 non-null   str
 8   Latitude         1000 non-null   float64
 9   Longitude        1000 non-null   float64
 10  Purchase_Amount  1000 non-null   float64
 11  Feedback         1000 non-null   str
dtypes: float64(5), int64(1), str(6)
memory usage: 144.4 KB

In [83]:
df.head(10)

,Customer_ID,Name,Age,Gender,Department,Monthly_Income,City,Customer_Type,Latitude,Longitude,Purchase_Amount,Feedback
0,1630,Aarav Jadhav,36.0,Female,Finance,110390.0,Ahmednagar,New,17.536043,75.505984,62663.45,Good
1,1789,Neha Sharma,32.0,Female,Operations,39371.0,Ahmednagar,Regular,20.073236,75.947597,31790.01,Excellent
2,1685,Amit Joshi,53.0,Male,Marketing,38204.0,Kolhapur,New,20.852464,75.521740,91180.51,Average
3,1517,Amit Deshmukh,33.0,Female,Data Analytics,50382.0,Nagpur,Premium,20.430885,77.862365,1535.62,Average
4,1530,Rahul Pawar,58.0,Female,Operations,70249.0,Aurangabad,New,17.555342,73.493211,26105.84,Good
5,1658,Meera Deshmukh,20.0,Female,IT,100830.0,Pune,New,20.350474,77.538260,48388.21,Good
6,1553,Sahil Deshmukh,47.0,Male,Operations,97557.0,Nagpur,Premium,17.175570,74.113904,31360.94,Poor
7,1532,Rahul More,53.0,Female,IT,32625.0,Nashik,New,21.410931,73.847627,60632.00,Excellent
8,1322,Isha Pawar,47.0,Female,Marketing,17014.0,Thane,Regular,20.462318,76.650566,88415.84,Good
9,1071,Nikhil Chavan,43.0,Female,Data Analytics,82193.0,Aurangabad,Regular,17.333136,77.205317,30187.15,Poor

In [84]:
df.tail()

,Customer_ID,Name,Age,Gender,Department,Monthly_Income,City,Customer_Type,Latitude,Longitude,Purchase_Amount,Feedback
1005,1107,Meera Chavan,46.0,Male,IT,49671.0,Pune,Regular,19.081121,78.961383,17574.52,Poor
1006,1271,Sahil Joshi,24.0,Male,Marketing,25490.0,Mumbai,Premium,18.551581,76.760438,17463.15,Very Good
1007,1861,Kavya Kulkarni,44.0,Male,Finance,31009.0,Kolhapur,New,16.723412,75.077469,41198.81,Poor
1008,1436,Riya Patil,20.0,Male,Operations,15868.0,Ahmednagar,Regular,18.147135,75.114177,10314.42,Average
1009,1103,Priya Deshmukh,36.0,Female,IT,38839.0,Pune,Premium,19.857801,75.029936,8918.73,Very Good

In [86]:
df.to_csv("emp_data.csv", index=False)

In [87]:
cleaned_df = pd.read_csv("emp_data.csv")

print(cleaned_df.shape)
print(cleaned_df.isnull().sum().sum())
print(cleaned_df.duplicated().sum())

(1000, 12)
0
0